= Guix overlay for NixOS
:toc:


It's an overlay for installing Guix in NixOS.
Forked originally from link:https://github.com/Emiller88/guix[Emiller88's Guix overlay].




== What's in the flake?

To quickly show the goods, just run `nix flake show ${FLAKE}`.

Here's what the flake should contain from the most interesting to the most boring.

* `overlays.default` which contains the overlay for the Guix (and its dependencies) as a Nix package.

* `packages.${system}.${package}` containing derivations of Guix and the dependencies.

* `nixosModules` contains various link:./modules/nixos/[NixOS modules] exported for this project.
The most useful (and only) modules are for enabling Guix daemon (either with the link:./modules/nixos/guix.nix[Nix-built version] or the link:./modules/nixos/guix-binary.nix[binary installation]).

* `devShells.${system}.guix` is the development shell for Guix project.
It is useful for making a quick start for link:https://guix.gnu.org/en/manual/en/html_node/Contributing.html#Contributing[contributing into the project].

Please see link:./flake.nix[`./flake.nix`] for more details.




== Prerequisites

You need Nix 2.8 and above with the Nix flakes and the new command line interface enabled.
To enable them, you need to add `experimental-features = nix-command flakes` from your Nix configuration (e.g., `/etc/nix/nix.conf`).

Now, to add it in your flake configuration...

[source, nix]
----
inputs.guix-overlay.url = "github:foo-dogsquared/nix-overlay-guix";
----

...and add the overlay in `nixpkgs.overlays`.

[source, nix]
----
nixpkgs.overlays = [
  # Your overlays...

  # The guix overlay.
  inputs.guix-overlay.overlays.default
];
----

You can add Guix as a additional package or as an additional service to your NixOS systems.

[source, nix]
----
# configuration.nix
{
  # ...the rest of your NixOS system config.

　# Enabling the Guix daemon and the package manager in your system.
  services.guix.enable = true;
}
----


== Development guidelines

Non-exhaustive list of guidelines when developing this project.

* This project follows the link:https://semver.org/[Semantic Versioning] scheme for its stable version.

* Follow the conventions in most NixOS modules from link:https://github.com/NixOS/nixpkgs/[nixpkgs] as of the appropriate version.

* Keep in mind about the main nixpkgs branch to be followed.
This is seen in link:./flake.nix[./flake.nix].

* For other stable versions, this should be kept at a separate branch similar to how nixpkgs and link:https://github.com/nix-community/home-manager/[home-manager] does it.




== Why fork it?

* First and foremost, I want to explore how to make an overlay like this.
I want the two package manager work together without much trouble (in the side of NixOS anyways).

* Try to make Guix work on a NixOS-based system.
I want it to make my Guix workflow works without resorting to virtual machines.
My workstation is just a potato ran by a hamster that is nearing its life expectancy and I cannot afford it any longer.
I WANT IT TO JUST WORK!

* Well, the original repository doesn't see much additional commits in the last year.
In that timeframe, Guix v1.3.0 has been released and more features is yet to be seen such as the Guix home configurations and additional fixes and small-scale features.
I don't want to miss out with another clunky virtual machine that is just further making my battery drain more.


=== TODO

* [ ] Cleanup the codebase.
** [x] Cleanup the additional Guile modules.
** [x] Format with `nixfmt`.

* [x] Document the flake and its outputs.

* [ ] Make it compatible with the traditional `default.nix`.
** [ ] Use link:https://github.com/edolstra/flake-compat[this module].

* [x] Cache the package set of this project.

* [x] Make use of a CI system to automate building and updating.

* [x] Create packages for Guix with the binary installation.
** [ ] Create the binary installation with various versions just for fun ;p
** [ ] Make the same with Nix-built Guix with offering the various versions.


=== Issues

The biggest issue is the Nix-built Guix won't use substitutes.
(IT'S A SECRET AMBUSH FROM THE NIX COMMUNITY SO THAT GUIX WON'T SUCCEED BY MAKING IT UNUSABLE WHEN USED INSIDE NIXOS! footnote:[That or I'm just incompetent at making this work.])
Most of the functionalities are fine and working — it can build packages from source, add them to the store, resolve dependencies, and does Guix things... except use the substitutes itself which hinders most of the usability.

For more information, see link:https://github.com/bqv/guix/issues/2[this issue from the original repo] which highlights similar experiences.
I've tested with the same methods from the linked issue: with different store directory and configuring the environment.
Even went to install Guix through Guix (which can take another few hours to take especially from SCRATCH!).
None of them worked so far.

In the mean time, I'll try to keep the package updated especially with the upcoming release of v1.4.0 (as of 2022-01-20).
In the end, I took the lazy route of installing with the binary installation (I'm sorry >_<).
I also made a package for Guix with the binary installations (but it is practically useless without using the link:./modules/nixos/guix-binary.nix[appropriate NixOS module]).
