name: "Build and push to binary cache"
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nixpkgs-branch:
          - nixos-unstable
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            keep-going = true
      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/guix-unstable' }}
        with:
          name: foo-dogsquared
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: "guix-binary"
      - name: Build custom packages
        run: nix build --file ./pkgs --override-input nixpkgs github:NixOS/nixpkgs/${{ matrix.nixpkgs-branch }} guix
